name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv install
      - name: Lint with flake8
        run: flake8 .
      - name: Type check with mypy
        run: mypy .
      - name: Test with coverage
        run: pytest --cov=./ --cov-report=term-missing
